version: '3'

services:
  web4:
    build: .
    restart: unless-stopped
    expose:
      - 5000
    volumes:
      - ./static:/root/static
      - ./templates:/root/templates
    networks:
      ctfnet:
        ipv4_address: 10.0.0.54

networks:
  ctfnet:
    external: true
